spring.application.name=HelpDesk

spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk
spring.datasource.username=ibrahim
spring.datasource.password=helpdesk123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true